""" add value column to alerts

Revision ID: 07c78f2446a6
Revises: 6007935aeddf
Create Date: 2026-05-13 14:48:40.933842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c78f2446a6'
down_revision: Union[str, None] = '6007935aeddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'value')
    # ### end Alembic commands ###
