""" increase api_key length

Revision ID: 6007935aeddf
Revises: 32cdfe95e704
Create Date: 2026-04-04 16:30:37.409464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6007935aeddf'
down_revision: Union[str, None] = '32cdfe95e704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'api_key',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'api_key',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
